DROP DATABASE IF EXISTS ict_lez09_oto;
CREATE DATABASE ict_lez09_oto;
USE ict_lez09_oto;

CREATE TABLE Persona(
	personaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    nominativo VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE,
    telefono VARCHAR(250) DEFAULT "N.D."
);

CREATE TABLE CartaIdentita(
	cartaidentitaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    codice VARCHAR(250) NOT NULL UNIQUE,
    personaRIF INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (personaRIF) REFERENCES Persona(personaID) ON DELETE CASCADE
);